import 'package:hanzishu/engine/localization.dart';

// NOTE: never change or remove an existingxx entry here. Just create a new one.
// ignore: non_constant_identifier_names
var theString_en_US = [
  Local(0, "Unknown"),
  Local(1, "Puzzle Game"), //Literacy tree
  Local(2, "Flashcards"),
  Local(3, "Word breakdown"),
  Local(4, "Conversation"),
  Local(5, "Typing exercises"),
  Local(6, "Quiz"), // Quiz
  Local(7, "Lesson"),
  Local(8, "Welcome to lesson "),
  Local(9, "Unit"),
  Local(10, "Hanzishu"),
  Local(11, "Basic"),
  Local(12, "In the classroom"),
  Local(13, "Family and friends"),
  Local(14, "Food"),
  Local(15, "Studies"),
  Local(16, "Weather"),
  Local(17, "Shopping"),
  Local(18, "Travel"),
  Local(19, "Transportation"),
  Local(20, "Sports and entertainment"),
  Local(21, "Hello"),
  Local(22, "Numbers"),
  Local(23, "Age"),
  Local(24, "Goodbye"),
  Local(25, "Classmates"),
  Local(26, "Thanks"),
  Local(27, "Apology"),
  Local(28, "China"),
  Local(29, "Name"),
  Local(30, "Start class"),
  Local(31, "Understanding"),
  Local(32, "Done"),
  Local(33, "Questions"),
  Local(34, "Reading"),
  Local(35, "Repetition"),
  Local(36, "Wait a minute"),
  Local(37, "Love"),
  Local(38, "Older brother"),
  Local(39, "Class"),
  Local(40, "Birthdays"),
  Local(41, "Feeling sick"),
  Local(42, "Meal"),
  Local(43, "Drinking"),
  Local(44, "Roast duck"),
  Local(45, "Spicy food"),
  Local(46, "Ordering"),
  Local(47, "Hanzi Tree"),
  Local(48, "Chinese words"),
  Local(49, "College"),
  Local(50, "Chinese"),
  Local(51, "Accommodations"),
  Local(52, "Homework"),
  Local(53, "Likes"),
  Local(54, "Temperature"),
  Local(55, "Sunny"),
  Local(56, "Wind & rain"),
  Local(57, "Seasons"),
  Local(58, "Snowing"),
  Local(59, "Cost"),
  Local(60, "Tickets"),
  Local(61, "Clothes"),
  Local(62, "Apartment"),
  Local(63, "Go shopping"),
  Local(64, "Restroom"),
  Local(65, "Sightseeing"),
  Local(66, "Directions"),
  Local(67, "Travel"),
  Local(68, "Photos"),
  Local(69, "Hotel"),
  Local(70, "Highspeed train"),
  Local(71, "Taxi"),
  Local(72, "Airplane"),
  Local(73, "Subway"),
  Local(74, "Start time"),
  Local(75, "Football"),
  Local(76, "Movie"),
  Local(77, "The Beijing Opera"),
  Local(78, "Song"),
  Local(79, "Dancing"),
  Local(80, "Pets"),
  Local(81, "Basic words (Chinese alphabets)"),
  Local(82, "Basic Non-words (Chinese alphabets)"),
  Local(83, "Words"),
  Local(84, "Word Groups"),
  Local(85, "Sound"),
  Local(86, "Meaning"),
  Local(87, "Strokes"),
  Local(88, "Strokes"),
  Local(89, "Hanzishu typing code"), //Pictographic typing code
  Local(90, "Hint"),
  Local(91, "Lessons"),
  Local(92, "Dictionary"),
  Local(93, "Typing"),
  Local(94, "More"),
  Local(95, "Hanzishu Dictionary"),
  Local(96, "First-Hanzi Radical Table"),
  Local(97, "Chinese alphabets"),
  Local(98, "Hanzi pictographic typing method"),
  Local(99, "[For below, please make sure your computer/phone is under English input mode. The program for the pictographic input method is built in here already."),
  Local(100, "Give it a try"),
  Local(101, "Chinese alphabet-key pairing groups"),
  Local(102, "Memorize by groups"),
  Local(103, "Learn Chinese alphabet-key pairings"),
  Local(104, "Guided typing"),
  Local(105, "Learn Chinese alphabets"),
  Local(106, "Typing exercises"),
  Local(107, "Exercises -- commonly used Hanzi"),
  Local(108, "Editor"),
  Local(109, "Try a few"),
  Local(110, "Let's try to type a few Hanzi.\n\n\Notes:\n\n 1) There are five different modes of hints, from hint 3 with full answer to game mode with no help. You can switch the modes as you need. \n\n2) If you are not sure about which letter to type, you can also guess clicking one of the four listed groups of Chinese alphabets, a green color indicates a correct guess, and a red color indicates a wrong guess. Then you can further guess clicking which type of Chinese alphabet it is."),
  Local(111, "Reference this chart to visualize how Chinese alphabets are mapped to English letters. The five single-stroke Chinese alphabets sit in the two middle columns, so try to read from middle to two sides."),
  Local(112, "Commonly used word exercises"),
  Local(113, "Type"),
  Local(114, "Help"),
  Local(115, "Good job!"),
  Local(116, "You did it! Let's go through the Chinese alphabet-key pairings now."),
  Local(117, "You did it again! Let’s get to know the Expanded Chinese alphabets."),
  Local(118, "Congratulations"),
  Local(119, "You are making great progress in typing Chinese words."),
  Local(120, "Your typing exercise is complete for this lesson."),
  Local(121, "Ready to memorize the Chinese alphabet-key pairings?"),
  Local(122, "The pairings are divided into six groups (based on the first Stroke of each Chinese alphabet). Five single-stroke ZiGroupPages are located in the middle, therefore remember each group from middle to two sides."),
  Local(123, "Learn the above groups."),
  Local(124, "Learn the above Chinese alphabet-key pairing groups."),
  Local(125, "The previous exercise introduced you to the Chinese alphabet-key pairings by group. In this exercise, you’ll memorize the Chinese alphabets within each group."),
  Local(126, "The above chart shows the mappings of 25 Chinese alphabets to upper case letters in a keyboard.\n\nLet's take a moment to memorize the above mappings now since a standard keyboard only shows letters. After that, click 'Continue' to test it out.\n"),
  Local(127, ""),
  Local(128, "Please tap or mouse click a key image below that maps the above Chinese alphabet."),
  Local(129, "Please review above given type of Chinese alphabets, then mouse click or tap their mapping key letter in the screen below."),
  Local(130, "Please choose the key group that matches the above Chinese alphabet group."),
  Local(131, "Step 3:\n\nQuestion: There are over couple hundreds of common Chinese alphabets and only 26 letters, how do I map all those Chinese alphabets?\n\nAnswer: All Chinese alphabets of same type map to one letter.\n\nThe above chart shows all Chinese alphabets of 'human legs' type. They share a same keyboard key letter of 'A'."), // not enough space for /*\n\nWe'll go through details of 25 types of Chinese alphabets.*/
  Local(132, "Note: The Expanded Chinese alphabets have similar shapes to their Lead Chinese alphabet."), // TODO: not used
  Local(133, "You remember the Chinese alphabets by group! In the next exercise, you will review the Chinese alphabets."),
  Local(134, "Way to go!"),
  Local(135, "You know types of Chinese alphabets now! Let’s test your knowledge with some guided typing."),
  Local(136, "Wow!"),
  Local(137, "You know Chinese alphabets now! Let’s use them in next exercise."),
  Local(138, "Next"),
  Local(139, "Word drill Hanzishu lesson review"),
  Local(140, "Glossary"),
  Local(141, "Privacy policy & contact us"),
  Local(142, "About the Hanzishu Dictionary"),
  Local(143, "The main Hanzishu Dictionary is organized according to the shape order. Its radicals are based on the basic character-forming components (roughly single body words). Its main characteristic is that the radical of each word is the the first radical that the word contains. It houses nearly 3,800 Chinese words and 50,000 phrases."),
  Local(144, "How to search a target word?"),
  Local(145, "1. Enter the main page of the dictionary - Open the radical table. (The numbers in the table represent the stroke count of radicals.)"),
  Local(146, "2. Choose radical"),
  Local(147, "a. If the target word contains both radical '口' and other radicals, tap the first other radical;"),
  Local(148, "ex: For Word '听', its first radical is '斤' (skip '口')"),
  Local(149, "a. If the target word contains radicals, tap the first radical;"),
  Local(150, "Ex: For Word '涨', its first radical is '弓'"),
  Local(151, "b. If the target word doesn’t contain any word radical, tap the stroke radical corresponding to the word's first stroke (The first five radicals in table are the stroke radicals)."),
  Local(152, "Ex: For Word '扎', its first stroke is '一';"),
  Local(153, "Ex: For word '丝', its first stroke is '乙'."),
  Local(154, "3. Choose the target word from the candidate list"),
  Local(155, "If the candidate list doesn't contain the target word, the dictionary doesn't support this word."),
  Local(156, "What are Chinese alphabets?"),
  Local(157, "Components are elements of a word. The Hanzishu pictographic typing method breaks Components into two types， Lead Components and various Expanded Components. Each Lead Component houses a collection of Expanded Components."),
  Local(158, "How it works"),
  Local(159, "The Hanzishu pictographic typing method matches each Lead Component with a key on the English keyboard to create a Component-key pairing. Reference this chart to visualize how Lead Components are mapped to English letters."),
  Local(160, "According to the most significant characteristics of the Expanded Components, assign theme to Lead Component-key pairings. To type a Chinese character, first break a character into a sequence of Components， then the sequence of Components are converted into sequences of English letters to be entered into computer. For a character group, type the up to first two letters for each character if it's two-character group, and type first letter of each chacacter for character group containing more than 2 characters."),
  Local(161, "The Hanzishu pinxing typing method section of this app will:"),
  Local(162, "Introduce you to Lead Components & various Expanded Components"),
  Local(163, "Teach you the Component-key pairings and typing method"),
  Local(164, "Help you memorize the Component-key pairings"),
  Local(165, "Help and guide you practice typing"),
  Local(166, "By the time you finish, you’ll be ready to type in Chinese on your own!"),
  Local(167, "Tips"),
  Local(168, "Tip 1: Want to use what you type elsewhere? Double click the content in the editing field to copy. Or you can install a standalone Hanzishu Pictographic Typing app into your computer."),
  Local(169, "Tip 2: The Dos and Don’ts of breaking up a word into Components："),
  Local(170, "DON’T break up Strokes that cross through each other (ok for two strokes that are next to each other or just touching)"),
  Local(171, "ex: Word 井 doesn’t split into separate Components"),
  Local(172, ""), //DO break up two strokes that are next to each other or just touching.
  Local(173, "ex: 明 -> 日 and 月"),
  Local(174, "ex: 古 -> 十 and 口"),
  Local(175, "DO break up words into as few Components as possible."),
  Local(176, "ex: 房 -> 户 and 方 (instead of four Components)"),
  Local(177, "DO break up with Components positioned earlier as many strokes as possible."),
  Local(178, "ex: 夏 -> first Component has two strokes instead of one"),
  Local(179, "Tip 3: The Lead Components and their keyboard pairings are visualized on the keyboard chart above."),
  Local(180, "Tap each Lead Component in the chart to see the Expanded Components associated to them."),
  Local(181, "During typing, select upper case letter 'Z' to show the Component-key pairings. Select upper case letter 'A' to 'Y' to show the Expanded Components. （only apply within this teaching course.)"),
  Local(182, "To type a Lead Component or its Expanded Component, simply type the corresponding keyboard key."),
  Local(183, "Tip 4: The rules to break a Component into Supplementary Components."),
  Local(184, "How to type a Chinese word"),
  Local(185, "Divide the word into ZiGroupPages (Lead Components or various Expanded Components)."),
  Local(186, "If a word has one Component:"),
  Local(187, "Type the Component"),
  Local(188, "If the word doesn’t appear on the list, type up to two make-up keys (the first and second Supplementary Components of the Component) until the Character appears"),
  Local(189, ""),
  Local(190, ""),
  Local(191, "If a word has two Components:"), //Obsolete
  Local(192, "Type the two Components first"), //Obsolete
  Local(193, "If the word doesn’t appear on the list, type up to two make-up keys (the first and second Supplementary Components of the second Component) until the Character appears"), //Obsolete
  Local(194, ""),
  Local(195, ""),
  Local(196, "If a word has three or more Components:"), //Obsolete
  Local(197, "Type as many Components as necessary in sequence."),
  Local(198, "In action"),
  Local(199, "Ex: Type the Chinese word 品"),
  Local(200, "Find the first Component 口"),
  Local(201, "Find the corresponding key i"),
  Local(202, "Tap it"),
  Local(203, "If 品 appears in the word list (below the editing field), select it by:"),
  Local(204, "Tapping the word"),
  Local(205, "Tapping the spacebar if it’s first in the list"),
  Local(206, "Typing the number associated with the word"),
  Local(207, "If the word is not listed, repeat these steps with the second and third Components until you see 品 listed"),
  Local(208, "The English letters in the editing field automatically convert to 品."),
  Local(209, "Terminology"),
  Local(210, "Hanzi"),
  Local(211, "Chinese word"),
  Local(212, "Hanzishu"),
  Local(213, "Hanzishu literally translates to ‘Chinese word tree’. Hansizhu is a learning method which breaks up Chinese Characters into Components. This system is used to search through the Chinese dictionary as well as to teach reading and typing in Chinese."),
  Local(214, "Strokes"),
  Local(215, "The lines used to create a word (or a Component)."),
  Local(216, "Components"),
  Local(217, "Elements of a word. There are two types of Components:"),
  Local(218, "Components that are also words (Basic words)"),
  Local(219, "Non-word Components. They require other Components to create a word."),
  Local(220, "Basic words"),
  Local(221, "Standalone Components. Basic words are the foundation of the Hanzishu Dictionary."),
  Local(222, "Words"),
  Local(223, "Words are created with Components or Strokes."),
  Local(224, "Lead Components"),
  Local(225, "The basic Components which are mapped to a key on the English keyboard."),
  Local(226, "Select upper case letter 'Z' to show the Component-key pairings while typing. (Only apply to the typing course)"),
  Local(227, "Expanded Components"),
  Local(228, "The Components that stem from a Lead Component. Expanded Components usually have a similar shape to its Lead Component."),
  Local(229, "Select upper case letter 'A' to 'Y' to show the Expanded Components while typing. (Only apply to the typing course)"),
  Local(230, "Distinguish Components"),
  Local(231, "The ZiGroupPages used to help to complete typing of words which contains only one or two Components."),
  Local(232, "Component/key pairing"),
  Local(233, "A Lead Component and its corresponding key on the English keyboard."),
  Local(234, "Mapping"),
  Local(235, "The concept of matching Lead Components to the English keyboard."),
  Local(236, "Hanzishu pictographic typing method"),
  Local(237, "A methodology of learning and typing Chinese by breaking up words into Components and mapping those core Components (Lead Components) to the English keyboard. All other Components (Expanded Components) are sorted under each Lead Component (often with a similar shape). Components are grouped into sequences of English letters. These sequences create Characters. Typing course supports nearly 3,800 commonly used Characters, and general purpose typing app supports 7,000 words."),
  Local(238, "A separate general purpose IME app for the typing method to be used by other programs is available for Windows and Mac computers now. Phone versions are close to complete."),
  Local(239, "Hanzishu Dictionary"),
  Local(240, "A Chinese word dictionary that’s organized based on Basic words. Searching a words by searching the first Basic words it contains."),
  Local(241, "Sections"),
  Local(242, "Lessons"),
  Local(243, "Practice your Chinese with 10 units of lessons (60 lessons total)."),
  Local(244, "Please return to this section once you have mastered the Hanzishu pictographic typing method."),
  Local(245, "word drills"),
  Local(246, "Learn words via a navigation tree. Includes definition, pronunciation, writing how-to, and the Basic words. It is a recursive tree with Components forming complicated Characters. It is visualized with the Character in the center of the screen and the Components/Characters (situated on all four sides of the screen) building up the central Character one layer at a time. Tapping a Character in the center drills down, and tapping a Component/Character on the sides moves back. Holding a Character/Component displays its detailed information."),
  Local(247, "Flashcards"),
  Local(248, "Reviews all the new Basic words, non-words, and phrases from a lesson. Includes pronunciation, definition, strokes, and the Component-key pairing sequence."),
  Local(249, "word breakdown"),
  Local(250, "Separates words in a lesson into words or Components. Tapping a word or a Component displays its detailed information."),
  Local(251, "Conversation"),
  Local(252, "Demonstrates pronunciation and provides speaking practice. Tapping a word displays its overlay information."),
  Local(253, "Typing exercises"),
  Local(254, "Practice for typing the word using the Hanzishu pictographic typing method."),
  Local(255, "Quiz"), // Quiz
  Local(256, "Reviews the lesson."),
  Local(257, "Dictionary"),
  Local(258, "View all the words based on the Hanzishu Dictionary method which groups words by their Basic words. Contains nearly 3,800 words."),
  Local(259, "Reference the Dictionary as you learn the Hanzishu pictographic typing method and complete the lessons."),
  Local(260, "Typing"),
  Local(261, "Learn the Hanzishu pictographic typing method and memorize the Component-key pairings."),
  Local(262, "Start in this section before continuing to the Lessons section."),
  Local(263, "More"),
  Local(264, "Hanzishu's other tools."),
  Local(265, "Word review"),
  Local(266, "Review the words according to the lessons and the units that they were first introduced."),
  Local(267, "Quiz results"), // Quiz
  Local(268, "Records of the quizzes that you have taken"),
  Local(269, "Icons"),
  Local(270, "Triangle"),
  Local(271, "Indicates a new word or Component in the lesson."),
  Local(272, "Pencil"),
  Local(273, "Tap to draw the word or ZiGroupPage"),
  Local(274, "Speaker"),
  Local(275, "Tap to hear the Component, the word or sentence"),
  Local(276, "Check mark"),
  Local(277, "Indicates that you have just gone through this word or Component."),
  Local(278, "Overlay"),
  Local(279, "Tapping or holding a word in many features within the app displays the detailed information about that Character."),
  Local(280, "Reminder: You should finish the typing course from the main menu before this exercise."),
  Local(281, "Note: Type uppercase letter Z to show Chinese alphabets to keyboard mapping."),
  Local(282, "Note: Type uppercase letter A to Y to show Expanded Components. Type Z to show mapping."),
  Local(283, "Incorrect."),
  Local(284, "Correct! "),
  Local(285, "Continue"),
  Local(286, "Ok"),
  Local(287, "You’ve mastered all six Component groups! In the next exercise, you will memorize the Components in each group."),
  Local(288, "Exercise selection"),
  Local(289, "Practice typing 3,800 Chinese words in 38 exercises，with each containing about 100 words."),
  Local(290, "Review selection"),
  Local(291, "Starting Unit"),
  Local(292, "Ending Unit"),
  Local(293, "Starting Lesson"),
  Local(294, "Ending Lesson"),
  Local(295, "Lesson"),
  Local(296, "Review"),
  Local(297, "Hanzishu App doesn't collect sensitive user specific data."),
  Local(298, "Tap 人 in the list below."),
  Local(299, "Type 'r', spacebar."),
  Local(300, "spacebar."),
  Local(301, "Start"),
  Local(302, "Language setting"),
  Local(303, "Language in title:"),
  Local(304, "Breakdown"),
  Local(305, "Diamond"),
  Local(306, "To show the detailed breakdown info."),
  Local(307, "to"),
  // 308 not used anymore
  Local(308, "Practice Chinese alphabets"),
  Local(309, "For the above Expanded Component, guess its Lead Component and type corresponding key."),
  Local(310, "You know your Expanded Components! Let’s review them in next exercise."),
  Local(311, "You really know your Expanded Components! Let’s practice with some typing exercises."),
  Local(312, "Reminder: For a word containing a single Chinese alphabet, first type the alphabet, then if needed, you can continue to type up to three strokes of the character: 1st, 2nd and last stroke."),
  Local(313, "Reminder: For a word containing two Chinese alphabets, first type the two alphabets, then if needed, you can continue to type up to two strokes: the last stroke from the 1st Chinese alphabet, and the last stroke from the 2nd Chinese alphabet."),
  Local(314, "If there are two options to separate Chinese alphabets, choose the option that contains a Chinese alphabet with more strokes."),
  Local(315, "Single mouth"),
  Local(316, "Horizontal"),
  Local(317, "Open right"),
  Local(318, "Throw away"),
  Local(319, "T shape"),
  Local(320, "Ear"),
  Local(321, "Triangle"),
  Local(322, "Three legs"),
  Local(323, "Open left"),
  Local(324, "Pure dots"),
  Local(325, "Left & right legs"),
  Local(326, "Knife"),
  Local(327, "Up & down"), //Up & down mouths
  Local(328, "Learn more Chinese alphabets"),
  Local(329, "Learn Twin Components"),
  Local(330, "Learn Sub Components"),
  Local(331, "Words with single Chinese alphabets"),
  Local(332, "Words with two Chinese alphabets"),
  Local(333, "General Exercises"),
  Local(334, "Practice Chinese alphabets"),
  Local(335, "Let's type a few Hanzi.\n\nNotes:\n\n 1)The rules of Chinese alphabet order in a Hanzi: top before bottom; left before right; outside before inside.\n\n2)The rules to break up a Hanzi: only break up into Chinese alphabets; never break up two lines that are crossing through each other (ex: don't break up '十'); as fewer Chinese alphabets as possible.\n\n3) Typing phrases: for phrases with two characters, type first two components from each character; for phrases with three or more components, type one component from each character; in both cases, you can also type all components from each character.\n"),
  Local(336, "Let's do some typing exercises with the Chinese alphabets you have learned.\n\n"),
  Local(337, "Lead/Expanded Component might contain Twin Components, which look almost same. Use the same key of the Component to type the Twin Components. \n\nThe following chart shows two Components in key 'X' that own some Twin Components.\n\nWe'll go through them.\n\n"),
  Local(338, "A Lead/Expanded Component might contain some subsets which are also Components. We call these subsets within a Chinese alphabet Sub Components, although they are also Components by definition. Use the same key of the Chinese alphabet to type those Sub Components. \n\nThe following chart shows the Components in key 'X' that contain Sub Components. We'll go through one key at a time.\n\n"),
  Local(339, "Step 4:\n\nQuestion: To speed up, can I type more letters for Hanzi which contains only single or two Chinese alphabets like '日' or '叶'?\n\nAnswer: Yes. For Hanzi '日', after you type its only alphabet '日' as usual, then if you want, you can continue to type up to two makeup alphabets of '日', which are '口' and '一'. That is, for Hanzi '日', you can type 日(B), 口(O), 一(E).\n\nThe so called makeup alphabets are just smaller alphabets breaking up from a given alphabet in order to speed up typing of single or double alphabet Hanzi. Note that word '日' contains only alphabet '日', while '口' and '一' are makeup alphabets, not regular alphabets of Hanzi '日'.\n\nFor '叶', you can get two make up alphabets from its second alphabet '十' by breaking up cross strokes into '一' and '丨' when there is no other options.\n\n"),
  //Local(339, "Part 5:\n\nQuestion: How do I type word '日' which is also a Chinese alphabet?\n\nAnswer: You type its only alphabet '日' as usual, then if needed, as a special case, you can continue to type up to two of alphabet 日's makeup alphabets, which are '口' and '一'. That is, you type 日(B), 口(O), 一(E).\n\nThe so called makeup alphabets are just subset of a alphabet that we use to distinguish single or double alphabet words. Note that word '日' contains only alphabet '日', and '口' and '一' are makeup alphabets, not word 日's regular alphabets. Also you can break up crossed strokes like '十' in order to get makeup alphabets if no other options.\n\n"),
  //Local(339, "For a character containing only one component, first type the component. After that, analyze the component to see which smaller components it contains, which are called Differentiate Components and type the first two.\n\nThe rules for analyzing a Component's Differentiate Components are same as for breaking up a character into Components, except that you can treat a component being consisted of Differentiate Components without breaking up crossed strokes， and when necessary separate crossed strokes.\n\nExample 1: To type a single-component character '日', first type Component '日'(B). After that, break up '日' into Differentiate Components '口' and '一', then type in '口'(O) and '一'(H). \n\nExample 2: To type a single-component character '十', first type Component '十'(K). After that, break up '十' into Differentiate Components '一' and '丨', then type in '一'(H) and '丨'(I). We'll go through some exercises."),
  Local(340, "Part 6:\n\nFor a word containing two Chinese alphabets, first type the two alphabets. After that, as a special case, you can continue to type the first two makeup alphabets of the second alphabet.\n\nFor example, to type '呆', first type in the two alphabets '口' and '木'. After that, find out the first two makeup alphabets '十' and '八' from the second alphabet '木', then type in '十'(K) and '八'(V) in. \n\nWe'll go through some exercises.\n\n"), /*During analyzing of a Component, a few fold strokes are not Components, and we match them to the closest Components as shown below.\n\n*/
  Local(341, "You have learned everything! Let's do some general exercises to complete the typing course.\n\n"),
  Local(342, "Vertical"),
  Local(343, "Break"),
  Local(344, "Grass"),
  Local(345, "Open up"),
  Local(346, "K shape"),
  Local(347, "Divided legs"),
  Local(348, "Open down"),
  Local(349, "Cliff"), // F
  Local(350, "Crossed legs"),
  Local(351, "Four mouths"),
  Local(352, "Mixed dots"),
  Local(353, "Human legs"),
  Local(354, "You have completed this exercise! Please move on to the next one."),
  Local(355, "Congratulation! You have completed this pictographic typing course! You can redo it, do some 'Commonly used character typing exercises', use editor here, or download general purpose Hanzishu pictographic typing program."),
  Local(356, "Expanded Components are very important! Let's practice them one more time before moving on.\n\nNote: Like English, a horizontal line in Chinese can only go from left to right, a vertical line can only go from top to bottom，and the two types of lines can connect together.\n\n"),
  Local(357, "Let's try it"),
  Local(358, "Please review the above mappings, then continue."),
  Local(359, "Please review the above mappings one more time, then continue."),
  Local(360, "Stroke categories"),
  Local(361, "Use this chart to choose the stroke category of a stroke"),
  Local(362, "Except following two points, other rules are same as the rules to break Chinese character into Components:"),
  Local(363, "If there are no other options, you can break up crossing strokes into individual strokes, which are also single stroke components)"),
  Local(364, "A few fold strokes should be treated as the closest Components as shown in the table below"),
  Local(365, "Introduction of the Hanzishu pictographic typing method"),
  Local(366, "The Hanzishu pictographic typing method breaks up a Chinese word into Components and types in the mapped letters on the English keyboard in order to type a Chinese character. The method doesn't break up crossing strokes of the character, therefore keep the wholeness of the components (more than half is single body character)."),
  Local(367, "If '品' is listed behind, you can continue to type in Components to move up its position"),
  Local(368, "Hanzishu pictographic typing method"),
  Local(369, "Components"),
  Local(370, "Please type"),
  Local(371, "Please type"),
  Local(372, "Recommend Chrome browser."),
  Local(373, "Snowball conversation"), //Unit
  Local(374, "Can not find character: "),
  Local(375, "Result"),
  Local(376, "minutes"),
  Local(377, "seconds"),
  Local(378, "English"),
  Local(379, "Download & use general purpose Hanzishu pictographic typing app"),
  Local(380, "Currently the general purpose Hanzishu pictographic typing app can be downloaded for Windows and Mac computers through http://github.com/hanzishu    That means, after installing the app, all other programs can use this typing method."),
  Local(381, "The development of the phone version of the app is close to complete."),
  Local(382, "At the same time, you can use the previous free typing page to type Chinese words then copy/paste to other programs."),
  Local(383, "Before moving to the next one, suggest you repeat this exercise until your progress is not obvious."),
  Local(384, "Chinese alphabets"),
  Local(385, "Name"),
  Local(386, "group"),
  Local(387, "unit"),
  Local(388, "Please learn and remember above general component categories carefully. It's the foundation of this method!"), // not used anymore
  Local(389, "Part 7:\n\nWe haven't learned some less commonly used alphabets as shown above.\n\nSince they are similar to the alphabets you have learned earlier, you should be able to recognize them. But let's go through them to speed up the learning process."),
  Local(390, "Attached components"), //not used anymore
  Local(391, "WOW！"),
  Local(392, "You know all the Components now! Next let's do some exercises."),
  Local(393, "Practice more Components"),
  Local(394, "Literacy Tree"), //"Hanzishu word puzzle"
  Local(395, "All 3,800 common Hanzi"),
  Local(396, "HSK Hanzi Study"),
  Local(397, "Up to "),
  Local(398, "Unit "),
  Local(399, "Level "),
  Local(400, "7/8/9"),
  Local(401, "Skip section"),
  Local(402, "Next section"),
  Local(403, "Individual exercises"),
  Local(404, "Study till all are check-marked"),
  Local(405, "Previous"),
  Local(406, "Customized flashcards"),
  Local(407, "You have completed all the flashcards!"),
  Local(408, "Copy/paste content here."),
  Local(409, "Study customized Hanzi"),
  Local(410, "You have completed this component typing exercise. Please move on to next one."),
  Local(411, "Hanzishu Introduction"),
  Local(412, "Hanzishu is a complete set of Chinese language learning methods and tools that are based on the shapes, components, and sound of Chinese words. You will learn Chinese fast through this system. \n\nHanzishu has iPhone App Store version, Android Google Play version and Hanzishu web version."),
  //Local(412, "Hanzishu is a complete set of Chinese language learning methods and tools that are based on the shapes, components, and sound of Chinese words.\n\nThe Hanzishu puzzle typing method, dictionary, word puzzle, and conversational lessons were invented and developed by Microsoft Senior Engineer John Zhongqi Wang. The Paint Sound symbols and lessons were invented by children education expert Kang Baoling.\n\nYou will learn Chinese fast through this system. Non-Chinese heritage students should start from conversation, and Chinese heritage students should start from Paint Sound section directly.\n\nHanzishu has iPhone App Store version, Android Google Play version and Hanzishu web version."),
  Local(413, "Exercises -- single alphabet words"), //"Typing exercises by component characteristics"
  Local(414, "Practice typing of all components by their characteristics."),
  Local(415, "Hanzishu pictographic typing course"),
  Local(416, "Please learn and remember above component categories, names and keyboard mapping carefully. It's the foundation of this method!"),
  Local(417, "For dictionary, pictographic typing, conversational lessons and more, choose the options from the bottom."),
  Local(418, "Phrases"),
  Local(419, "There are no phrases for this word in this system ."),
  Local(420, "Hanzishu Chinese Enlightening Classes"),
  Local(421, "Hanzishu's past and present history"),
  Local(422, "Paint Sound"),
  Local(423, "Intermediate: Stories"),
  Local(424, "Beginner：Children's songs"),
  Local(425, "Intermediate：Children's folks"),
  Local(426, "Advanced： Fairy tales"),
  Local(427, "Click each drawing and learn its sound:"),
  Local(428, "Exit this lesson"),
  Local(429, "Beginner: Conversation"),
  Local(430, "Exercises"),
  Local(431, "Expanded"),
  Local(432, "Please read aloud the following lesson, and point finger at each word while reading."),
  Local(433, "Previouw page"),
  Local(434, "Next page"),
  Local(435, "Makayla Chinese Learning Diary"),
  Local(436, "Hazishu pictographic typing method and Chinese teaching"),
  Local(437, "Pinyin does no good to international Chinese teaching"),
  Local(438, "Hint2"),
  Local(439, "Introduction to Hanzishu Pictographic Typing"),
  Local(440, "Hanzi structure"),
  Local(441, "Single part"),
  Local(442, "Left & right"),
  Local(443, "Up & down"),
  Local(444, "Wrapped"),
  Local(445, "Chinese alphabet count"),
  Local(446, "Breakdown"),
  Local(447, "Test Hanzi to Sound"),
  Local(448, "Test Hanzi Meaning"),
  Local(449, "Hanzi practice sheet generator"),
  Local(450, "Hanzishu unit review"),
  Local(451, "Notes: The above pulldown menu contains following items:"),
  Local(452, "Show Hanzi"),
  Local(453, "Not show Hanzi"),
  Local(454, "Hanzi practice sheet"),
  Local(455, "HSK Hanzi"),
  Local(456, "Puzzle Game"), // "Literacy tree/Learn or review Hanzi"
  Local(457, "In current test, it's estimated that you know about "),
  Local(458, "Total is "),
  Local(459, "All levels combined"),
  Local(460, "Mouth"),
  Local(461, "Legs"),
  Local(462, "Common"),
  Local(463, "Warning: Wrong typing code (ignore if typing a phrase)."),
  Local(464, "NoHint"),
  Local(465, "Direction"),
  Local(466, "Good effort"),
  Local(467, "You have passed this quiz with a score of"),
  Local(468, "You have achieved a score of"),
  Local(469, "You can come back later to reach 70."),
  Local(470, "Chinese alphabets"),
  Local(471, "New scientific stage of Chinese character education"),
  Local(472, "Chicken"),
  Local(473, "Camel"),
  Local(474, "Bear"),
  Local(475, "Terra-Cotta Warriors"),
  Local(476, "Mulan"),
  Local(477, "Shanghai"),
  Local(478, "lessonlevelstr478"),
  Local(479, "lessonlevelstr479"),
  Local(480, "lessonlevelstr480"),
  Local(481, "lessonlevelstr481"),
  Local(482, "Stories"),
  Local(483, ""),
  Local(484, "Your own preferred typing method"),
  Local(485, "Hanzishu Pictographic Typing method"),
  Local(486, "Please use following methods to search word"),
  Local(487, "(built-in, please set system input mode to English.)"),
  Local(488, "Test Sound to Hanzi"),
  Local(489, "Typing Hanzi"),
  Local(490, "Yuwen - Standard Textbook"),
  Local(491, "Listen and type Hanzi"),
  Local(492, "Hanzi: learn, flashcard, typing, and quiz."),
  Local(493, "Change method"),
  Local(494, "Pictographic typing method"),
  Local(495, "Self-chosen input methods"),
  Local(496, "Grade"),
  Local(497, "Semester"),
  Local(498, "Learn Hanzi"),
  Local(499, "Lesson"),
  Local(500, "Study Hanzi"),
  Local(501, "Snowball stories"),
  Local(502, "You have completed this typing exercise."),
  Local(503, "(under English mode)"),
  Local(504, "Friendly links"),
  Local(505, "Pinyin exercise"),
  Local(506, "Click each Pinyin and repeat after speaker for a few times."),
  Local(507, "No Pinyin"),
  Local(508, "First Only"),
  Local(509, "New Only"),
  Local(510, "Full Pinyin"),
  Local(511, "Pictographic Typing intro"),
  Local(512, "You have typed your first three Hanzi into computer!"),
  Local(513, "In this three-step typing course, you will learn how to type Hanzi (Chinese character) into computer using Hanzishu Pictographic Typing method.\n\nStep1:\n\nQuestion: How can I type Hanzi '口' into computer?\n\nAnswer: You find uppercase letter 'O' whose shape has similar characteristic as '口'， then type 'o'. \n\nThen choose '口' from a candidate list below the editing field by typing its number, mouse clicking, tapping it, or using space bar to choose the 1st candidate. You can also use arrow '>' key to see more candidates when necessary."),
  Local(514, "Step 2:\n\nQuestion: Can I map other Chinese alphabets to letters as well?\n\nAnswer: Yes. You can map all 4 groups, 25 types of Chinese alphabets to 25 upper case letters by shape similarity.\n\nLet's go through those types now."),
  Local(515, "Next"),
  Local(516, "Customized Typing Exercises"),
  Local(517, "Exercises -- Ty Textbook Typing"),
  Local(518, "Typing exercises"),
  Local(519, "Guess"),
  Local(520, "Textbook"),
  Local(521, "Alphabets"),
  Local(522, "Explanation"),
  Local(523, "Hint3"),
  Local(524, "Score"),
  Local(525, "Game"),
  Local(526, "Exercises -- Yuwen"),
  Local(527, "Note: hint unavailable for it."),
  Local(528, "Exercises -- Chinese Made Easy"),
];