import 'package:hanzishu/engine/localization.dart';

// NOTE: never change or remove an existing entry here. Just create a new one.
var theString_zh_CN = [
  Local(0, "XOK"),
  Local(1, "XCharacter drills"),
  Local(2, "XFlashcards"),
  Local(3, "XCharacter breakdown"),
  Local(4, "XConversation"),
  Local(5, "XTyping exercises"),
  Local(6, "XQuiz"),
  Local(7, "XLesson"),
  Local(8, "XPlease complete exercises in order."),
  Local(9, "XUnit"),
  Local(10, "XHanzishu"),
  Local(11, "XBasics"),
  Local(12, "XIn the classroom"),
  Local(13, "XFamily and friends"),
  Local(14, "XFood"),
  Local(15, "XStudies"),
  Local(16, "XWeather"),
  Local(17, "XShopping"),
  Local(18, "XTravel"),
  Local(19, "XTransportation"),
  Local(20, "XSports and entertainment"),
  Local(21, "XHello"),
  Local(22, "XNumbers"),
  Local(23, "XAge"),
  Local(24, "XGoodbye"),
  Local(25, "XClassmates"),
  Local(26, "XThanks"),
  Local(27, "XApology"),
  Local(28, "XChina"),
  Local(29, "XName"),
  Local(30, "XStart class"),
  Local(31, "XUnderstanding"),
  Local(32, "XDone"),
  Local(33, "XQuestions"),
  Local(34, "XReading"),
  Local(35, "XRepetition"),
  Local(36, "XWait a minute"),
  Local(37, "XLove"),
  Local(38, "XOlder brother"),
  Local(39, "XClass"),
  Local(40, "XBirthdays"),
  Local(41, "XFeeling sick"),
  Local(42, "XMeal"),
  Local(43, "XDrinking"),
  Local(44, "XRoast duck"),
  Local(45, "XSpicy food"),
  Local(46, "XOrdering"),
  Local(47, "XHanzi Tree"),
  Local(48, "XChinese characters"),
  Local(49, "XCollege"),
  Local(50, "XChinese"),
  Local(51, "XAccommodations"),
  Local(52, "XHomework"),
  Local(53, "XLikes"),
  Local(54, "XTemperature"),
  Local(55, "XSunny"),
  Local(56, "XWind & rain"),
  Local(57, "XSeasons"),
  Local(58, "XSnowing"),
  Local(59, "XCost"),
  Local(60, "XTickets"),
  Local(61, "XClothes"),
  Local(62, "XApartment"),
  Local(63, "XGo shopping"),
  Local(64, "XRestroom"),
  Local(65, "XSightseeing"),
  Local(66, "XDirections"),
  Local(67, "XTravel"),
  Local(68, "XPhotos"),
  Local(69, "XHotel"),
  Local(70, "XHighspeed train"),
  Local(71, "XTaxi"),
  Local(72, "XAirplane"),
  Local(73, "XSubway"),
  Local(74, "XStart time"),
  Local(75, "XFootball"),
  Local(76, "XMovie"),
  Local(77, "XThe Beijing Opera"),
  Local(78, "XSong"),
  Local(79, "XDancing"),
  Local(80, "XPets"),
  Local(81, "XBasic Characters (Components)"),
  Local(82, "XBasic Non-Characters (Components)"),
  Local(83, "XCharacters"),
  Local(84, "XCharacter Groups"),
  Local(85, "XSound"),
  Local(86, "XMeaning"),
  Local(87, "XStrokes"),
  Local(88, "XStrokes"),
  Local(89, "XTyping code"),
  Local(90, "XHint"),
  Local(91, "XLessons"),
  Local(92, "XDictionary"),
  Local(93, "XTyping"),
  Local(94, "XMe"),
  Local(95, "XFirst Character Dictionary"),
  Local(96, "XBasic Character Table"),
  Local(97, "XComponents"),
  Local(98, "XComponent Input Method"),
  Local(99, "XPlease finish exercise 1 - 7 to learn the input method"),
  Local(100, "XGive it a try"),
  Local(101, "XComponent-key pairing groups"),
  Local(102, "XMemorize by groups"),
  Local(103, "XMemorize the pairings"),
  Local(104, "XGuided typing"),
  Local(105, "XExpanded Components"),
  Local(106, "XTyping exercises"),
  Local(107, "X[Optional] Customized exercises"),
  Local(108, "XFree typing and help"),
  Local(109, "XTry a few"),
  Local(110, "XThe Component Input Method breaks up a Chinese Character into Components and types in the mapped letters on the English keyboard."),
  Local(111, "XReference this chart to visualize how Lead Components are mapped to English letters. The five single-stroke Components sit in the two middle columns, so try to read from middle to side."),
  Local(112, "XCustomized exercises"),
  Local(113, "XPlease type"),
  Local(114, "XHelp"),
  Local(115, "XGood job!"),
  Local(116, "XYou did it! Let's go through the Component-key pairings now."),
  Local(117, "XYou did it again! Let’s get to know the Expanded Components."),
  Local(118, "XCongratulations!"),
  Local(119, "XYou are making great progress in typing Chinese characters."),
  Local(120, "XYour typing exercise is complete for this lesson."),
  Local(121, "XReady to memorize the Component-key pairings?"),
  Local(122, "XThe pairings are divided into six groups (based on the first Stroke of each Component). Five single-stroke components are located in the middle, therefore remember each group from middle to sides."),
  Local(123, "XLearn the above groups."),
  Local(124, "XLearn the above Component-key pairing groups."),
  Local(125, "XThe previous exercise introduced you to the Component-key pairings by group. In this exercise, you’ll memorize the Components within each group."),
  Local(126, "XMemorize the above Component-key pairings."),
  Local(127, "XMemorize the above Component-key pairings."),
  Local(118, "XMap the Component to its key."),
  Local(129, "XGuess the Lead Component and corresponding key for these Expanded Components."),
  Local(130, "XMatch above Component group to its key group."),
  Local(131, "XThis chart shows the Expanded Components for Lead Component 日（key O). To type an Expanded Component, just type its Lead Component 日（key O)."),
  Local(132, "XNote: The Expanded Components have similar shapes to their Lead Component."),
  Local(133, "XYou remember the Components by group! In the next exercise, you will review the Components."),
  Local(134, "XWay to go!"),
  Local(135, "XYou know your Lead Components! Let’s test your knowledge with some guided typing."),
  Local(136, "XWow!"),
  Local(137, "XYou know your Expanded Components! Let’s practice with some typing exercises."),
  Local(138, "XNext"),
  Local(139, "XCharacter review"),
  Local(140, "XGlossary"),
  Local(141, "XPrivacy policy"),
  Local(142, "XAbout the First Character Dictionary"),
  Local(143, "XThe First Character Dictionary is organized according to the first Basic Character contained in a Character. It houses nearly 3,800 Characters, all listed under their corresponding Basic Character. Each number in the Basic Character Table represents the number of strokes for each Basic Character in that group."),
  Local(144, "XNavigate the First Character Dictionary"),
  Local(145, "XOpen the Basic Character Table"),
  Local(146, "XTap the first Basic Character of the Character that you are searching for"),
  Local(147, "XSelect the Character from the list. Note: If it’s not there, the dictionary doesn’t support this character."),
  Local(148, "XView the detailed information about the Character"),
  Local(149, "XIdentify the Character’s first Basic Character"),
  Local(150, "XEx: Character 你 -> Basic Character 小 (the first and only Basic Character)"),
  Local(151, "XIf a Character’s first Basic Character is 口, but it contains other Basic Characters, select the next Basic Character"),
  Local(152, "XEx: 听 -> 斤 (skip 口)"),
  Local(153, "XIf a Character doesn’t contain any Basic Characters, select the Character’s first stroke (in group 1)"),
  Local(154, "XEx: Character 扎 -> Stroke 一 "),
  Local(155, "XEx: Character 丝 -> Stroke 乙. Note: all fold strokes map to 乙."),
  Local(156, "XWhat are Components?"),
  Local(157, "XComponents are elements of a Character. The Hanzishu Component Input Method breaks Components into two types. Lead Components are the base Components. And each Lead Component houses a collection of sub-components called Expanded Components."),
  Local(158, "XHow it works"),
  Local(159, "XThe Hanzishu Component Input Method matches each Lead Component with a key on the English keyboard to create a Component-key pairing. Reference this chart to visualize how Lead Components are mapped to English letters."),
  Local(160, "XExpanded Components are grouped under each Lead Component-key pairing. To type in Chinese, Components are grouped into sequences of English letters. Each sequence of Components creates a Character."),
  Local(161, "XThe Typing section of this app will:"),
  Local(162, "XIntroduce you to Lead & Expanded Components"),
  Local(163, "XTeach you the Component-key pairings and typing method"),
  Local(164, "XHelp you memorize the Component-key pairings"),
  Local(165, "XHelp you practice with guided and free typing"),
  Local(166, "XBy the time you finish, you’ll be ready to type in Chinese on your own!"),
  Local(167, "XTips"),
  Local(168, "XTip 1: Want to use what you type elsewhere? Double click the content in the editing field to copy."),
  Local(169, "XTip 2: The Dos and Don’ts of breaking up a Character into Components."),
  Local(170, "XDON’T break up Strokes that cross through each other."),
  Local(171, "Xex: Character 井 doesn’t split into separate Components"),
  Local(172, "XDO break up two strokes that are next to each other or just touching."),
  Local(173, "Xex: 明 -> 日 and 月"),
  Local(174, "Xex: 古 -> 十 and 口"),
  Local(175, "XDO break up Characters into as few Components as possible."),
  Local(176, "Xex: 房 -> 户 and 方 (instead of four Components)"),
  Local(177, "XDO break up Characters into the Component with the most  strokes."),
  Local(178, "Xex: 云 -> 一 (plus another Component with three strokes)"),
  Local(179, "XTip 3: The Lead Components and their keyboard pairings are visualized on the keyboard chart above."),
  Local(180, "XTap each Lead Component in the chart to see the Expanded Components associated to them."),
  Local(181, "XDuring typing, select Shift+z to show the Component-key pairings. Select Shift+ any key (except z) to show the Expanded Components."),
  Local(182, "XTo type a Lead Component or its Expanded Component, simply type the corresponding keyboard key."),
  Local(183, "XTip 4: Use this table to learn all the Strokes."),
  Local(184, "XHow to type a Chinese Character"),
  Local(185, "XDivide the character into components (Lead Components or Expanded Components)."),
  Local(186, "XIf a Character has one Component:"),
  Local(187, "XType the Component"),
  Local(188, "XIf the Character doesn’t appear on the list:"),
  Local(189, "XType up to three make-up Strokes (the first, second, and the last stroke of the Component) until the Character appears"),
  Local(190, "XTreat all fold Strokes as a Component 乙"),
  Local(191, "XIf a Character has two Components:"),
  Local(192, "XType the two Components first"),
  Local(193, "XIf the Character doesn’t appear on the list:"),
  Local(194, "XType two make-up Strokes (the last Stroke of each Component) until the Character appears"),
  Local(195, "XTreat all fold Strokes as a Component 乙"),
  Local(196, "XIf a Character has three or more Components:"),
  Local(197, "XType as many Components as necessary in sequence until the Character appears"),
  Local(198, "XIn action"),
  Local(199, "XEx: Type the Chinese character 品"),
  Local(200, "XFind the first Component 口"),
  Local(201, "XFind the corresponding key i"),
  Local(202, "XTap it"),
  Local(203, "XIf 品 appears in the Character list (below the editing field), select it by:"),
  Local(204, "XTapping the Character"),
  Local(205, "XTapping the spacebar if it’s first in the list"),
  Local(206, "XTyping the number associated with the character"),
  Local(207, "XIf the Character is not listed, repeat these steps with the second and third Components until you see 品 listed"),
  Local(208, "XThe English letters in the editing field automatically convert to 品."),
  Local(209, "XTerminology"),
  Local(210, "XHanzi"),
  Local(211, "XChinese character"),
  Local(212, "XHanzishu"),
  Local(213, "XHanzishu literally translates to ‘Chinese character tree’. Hansizhu is a learning method which breaks up Chinese Characters into Components. This system is used to search through the Chinese dictionary as well as to teach reading and typing in Chinese."),
  Local(214, "XStrokes"),
  Local(215, "XThe lines used to create a Character (or a Component)."),
  Local(216, "XComponents"),
  Local(217, "XElements of a Character. There are two types of Components:"),
  Local(218, "XComponents that are also Characters (Basic Characters)"),
  Local(219, "XNon-Character Components. They require other Components to create a Character."),
  Local(220, "XBasic Characters"),
  Local(221, "XStandalone Components. Basic Characters are the foundation of the First Character Dictionary."),
  Local(222, "XCharacters"),
  Local(223, "XCharacters are created with Components or Strokes."),
  Local(224, "XLead Components"),
  Local(225, "XThe basic Components which are mapped to a key on the English keyboard."),
  Local(226, "XSelect Shift+z to show the Component-key pairings while typing."),
  Local(227, "XExpanded Components"),
  Local(228, "XThe Components that stem from a Lead Component. Expanded Components usually have a similar shape to its Lead Component."),
  Local(229, "XSelect Shift+ any key except z to show the Expanded Components while typing."),
  Local(230, "XMake-up Strokes"),
  Local(231, "XThe Strokes used to complete typing of Characters which contains only one or two Components."),
  Local(232, "XComponent-key pairing"),
  Local(233, "XA Lead Component and its corresponding key on the English keyboard."),
  Local(234, "XMapping"),
  Local(235, "XThe concept of matching Lead Components to the English keyboard."),
  Local(236, "XComponent Input Method"),
  Local(237, "XA methodology of learning and typing Chinese by breaking up Characters into Components and mapping those core Components (Lead Components) to the English keyboard. All other Components (Expanded Components) are sorted under each Lead Component (often with a similar shape). Components are grouped into sequences of English letters. These sequences create Characters. Supports nearly 3,800 Characters."),
  Local(238, "XA separate IME app for the input method to be used by other programs is under development and could be released at any time."),
  Local(239, "XFirst Character Dictionary"),
  Local(240, "XA Chinese Character dictionary that’s organized based on Basic Characters. Searching a Character by searching the first Basic Character it contains."),
  Local(241, "XSections"),
  Local(242, "XLessons"),
  Local(243, "XPractice your Chinese with 10 units of lessons (60 lessons total)."),
  Local(244, "XReturn to this section once you have mastered the Component Input Method."),
  Local(245, "XCharacter drills"),
  Local(246, "XOverview of Characters via a navigation tree. Includes definition, pronunciation, writing how-to, and the Basic Characters. It is a recursive tree with Components forming complicated Characters. It is visualized with the Character in the center of the screen and the Components/Characters (situated on all four sides of the screen) building up the central Character one layer at a time. Tapping a Character in the center drills down, and tapping a Component/Character on the sides moves back. Holding a Character/Component displays its detailed information."),
  Local(247, "XFlashcards"),
  Local(248, "XReviews all the new Basic Characters, non-characters, and phrases from a lesson. Includes pronunciation, definition, strokes, and the Component-key pairing sequence."),
  Local(249, "XCharacter breakdown"),
  Local(250, "XSeparates Characters in a lesson into Characters or Components. Tapping a Character or a Component displays its detailed information."),
  Local(251, "XConversation"),
  Local(252, "XDemonstrates pronunciation and provides speaking practice. Tapping a Character displays its overlay information."),
  Local(253, "XTyping exercises"),
  Local(254, "XPractice for typing the Character using the Component Input Method."),
  Local(255, "XQuiz"),
  Local(256, "XReviews the lesson."),
  Local(257, "XDictionary"),
  Local(258, "XView all the characters based on the First Character Dictionary method which groups Characters by their Basic Characters. Contains nearly 3,800 Characters."),
  Local(259, "XReference the Dictionary as you learn the Component Input Method and complete the lessons."),
  Local(260, "XTyping"),
  Local(261, "XLearn the Component Input Method and memorize the Component-key pairings."),
  Local(262, "XStart in this section before continuing to the Lessons section."),
  Local(263, "XMe"),
  Local(264, "XTrack your progress and review what you’ve already covered."),
  Local(265, "XCharacter review"),
  Local(266, "XReview the characters according to the lessons and the units that they were first introduced."),
  Local(267, "XQuiz results"),
  Local(268, "XRecords of the quizzes that you have taken"),
  Local(269, "XIcons"),
  Local(270, "XTriangle"),
  Local(271, "XIndicates a new Character or Component in the lesson."),
  Local(272, "XPencil"),
  Local(273, "XTap to see the Character drawn"),
  Local(274, "XSpeaker"),
  Local(275, "XTap to hear the Character"),
  Local(276, "XCheck mark"),
  Local(277, "XIndicates that you have just gone through this Character or Component."),
  Local(278, "XOverlay"),
  Local(279, "XTapping or holding a Character in many features within the app displays the detailed information about that Character."),
  Local(280, "XReminder: You should finish the typing course from the main menu before this exercise."),
  Local(281, "XNote: Type uppercase letter Z to show components to keyboard mapping."),
  Local(282, "XNote: Type uppercase letter A to Y to show Expanded Components. Type Z to show mapping."),
  Local(283, "XIncorrect."),
  Local(284, "XCorrect! "),
  Local(285, "XContinue"),
  Local(286, "XOk"),
  Local(287, "XYou’ve mastered all six Component groups! In the next exercise, you will memorize the Components in each group."),
  Local(288, "XExercise selection"),
  Local(289, "XPractice typing 3,800 Characters in 38 exercises"),
  Local(290, "XReview selection"),
  Local(291, "XStarting Unit"),
  Local(292, "XEnding Unit"),
  Local(293, "XStarting Lesson"),
  Local(294, "XEnding Lesson"),
  Local(295, "XLesson"),
  Local(296, "XReview"),
  Local(297, "XHanzishu App doesn't collect sensitive user specific data."),
  Local(298, "XTap 人 in the list below."),
  Local(299, "XType 'r', spacebar."),
  Local(300, "Xspacebar."),
  Local(301, "XStart"),
  Local(302, ""),
  Local(303, ""),
  Local(304, ""),
  Local(305, ""),
  Local(306, ""),
  Local(307, ""),
  Local(308, ""),
  Local(309, ""),
  Local(310, ""),
  Local(311, ""),
  Local(312, ""),
  Local(313, ""),
  Local(314, ""),
  Local(315, ""),
  Local(316, ""),
  Local(317, ""),
  Local(318, ""),
  Local(319, ""),
  Local(320, ""),
];