import 'package:hanzishu/engine/localization.dart';

// NOTE: never change or remove an existing entry here. Just create a new one.
var theString_en_US = [
  Local(0, "Unknown"),
  Local(1, "Character drills"),
  Local(2, "Flashcards"),
  Local(3, "Character breakdown"),
  Local(4, "Conversation"),
  Local(5, "Typing exercises"),
  Local(6, "Quiz"),
  Local(7, "Lesson"),
  Local(8, "Please complete exercises in order."),
  Local(9, "Unit"),
  Local(10, "Hanzishu"),
  Local(11, "Basics"),
  Local(12, "In the classroom"),
  Local(13, "Family and friends"),
  Local(14, "Food"),
  Local(15, "Studies"),
  Local(16, "Weather"),
  Local(17, "Shopping"),
  Local(18, "Travel"),
  Local(19, "Transportation"),
  Local(20, "Sports and entertainment"),
  Local(21, "Hello"),
  Local(22, "Numbers"),
  Local(23, "Age"),
  Local(24, "Goodbye"),
  Local(25, "Classmates"),
  Local(26, "Thanks"),
  Local(27, "Apology"),
  Local(28, "China"),
  Local(29, "Name"),
  Local(30, "Start class"),
  Local(31, "Understanding"),
  Local(32, "Done"),
  Local(33, "Questions"),
  Local(34, "Reading"),
  Local(35, "Repetition"),
  Local(36, "Wait a minute"),
  Local(37, "Love"),
  Local(38, "Older brother"),
  Local(39, "Class"),
  Local(40, "Birthdays"),
  Local(41, "Feeling sick"),
  Local(42, "Meal"),
  Local(43, "Drinking"),
  Local(44, "Roast duck"),
  Local(45, "Spicy food"),
  Local(46, "Ordering"),
  Local(47, "Hanzi Tree"),
  Local(48, "Chinese characters"),
  Local(49, "College"),
  Local(50, "Chinese"),
  Local(51, "Accommodations"),
  Local(52, "Homework"),
  Local(53, "Likes"),
  Local(54, "Temperature"),
  Local(55, "Sunny"),
  Local(56, "Wind & rain"),
  Local(57, "Seasons"),
  Local(58, "Snowing"),
  Local(59, "Cost"),
  Local(60, "Tickets"),
  Local(61, "Clothes"),
  Local(62, "Apartment"),
  Local(63, "Go shopping"),
  Local(64, "Restroom"),
  Local(65, "Sightseeing"),
  Local(66, "Directions"),
  Local(67, "Travel"),
  Local(68, "Photos"),
  Local(69, "Hotel"),
  Local(70, "Highspeed train"),
  Local(71, "Taxi"),
  Local(72, "Airplane"),
  Local(73, "Subway"),
  Local(74, "Start time"),
  Local(75, "Football"),
  Local(76, "Movie"),
  Local(77, "The Beijing Opera"),
  Local(78, "Song"),
  Local(79, "Dancing"),
  Local(80, "Pets"),
  Local(81, "Basic Characters (Components)"),
  Local(82, "Basic Non-Characters (Components)"),
  Local(83, "Characters"),
  Local(84, "Character Groups"),
  Local(85, "Sound"),
  Local(86, "Meaning"),
  Local(87, "Strokes"),
  Local(88, "Strokes"),
  Local(89, "Typing code"),
  Local(90, "Hint"),
  Local(91, "Lessons"),
  Local(92, "Dictionary"),
  Local(93, "Typing"),
  Local(94, "Me"),
  Local(95, "First Character Dictionary"),
  Local(96, "Basic Character Table"),
  Local(97, "Components"),
  Local(98, "Quanzi Input Method"),
  Local(99, "Please finish exercise 1 - 11 to learn the Quanzi Input Method"),
  Local(100, "Give it a try"),
  Local(101, "Component-key pairing groups"),
  Local(102, "Memorize by groups"),
  Local(103, "Learn Component-key pairings"),
  Local(104, "Guided typing"),
  Local(105, "Learn Expanded Components"),
  Local(106, "Typing exercises"),
  Local(107, "[Optional] Customized typing exercises"),
  Local(108, "Free typing and help"),
  Local(109, "Try a few"),
  Local(110, "The Quanzi Input Method breaks up a Chinese Character into Components and types in the mapped letters on the English keyboard.\n\nFor example, to type character '晶', you break it into '日', '日', and '日', then type 'B', 'B', and 'B', then choose '晶' from the candidate list below the editing field.\n\nThe order of rules to break up a character: Never break up two lines that are crossing through each other (ok for separated or touching lines); as fewer components as possible; prefer separated components; prefer components containing more strokes.\n\nYou can use 'Hint' when necessary.\n\n"),
  Local(111, "Reference this chart to visualize how Lead Components are mapped to English letters. The five single-stroke Components sit in the two middle columns, so try to read from middle to two sides."),
  Local(112, "Customized exercises"),
  Local(113, "Please type"),
  Local(114, "Help"),
  Local(115, "Good job!"),
  Local(116, "You did it! Let's go through the Component-key pairings now."),
  Local(117, "You did it again! Let’s get to know the Expanded Components."),
  Local(118, "Congratulations!"),
  Local(119, "You are making great progress in typing Chinese characters."),
  Local(120, "Your typing exercise is complete for this lesson."),
  Local(121, "Ready to memorize the Component-key pairings?"),
  Local(122, "The pairings are divided into six groups (based on the first Stroke of each Component). Five single-stroke components are located in the middle, therefore remember each group from middle to two sides."),
  Local(123, "Learn the above groups."),
  Local(124, "Learn the above Component-key pairing groups."),
  Local(125, "The previous exercise introduced you to the Component-key pairings by group. In this exercise, you’ll memorize the Components within each group."),
  Local(126, "Let's take a moment to memorize the above Component-key pairings which is the foundation. After that, click Next to test it out.\n\n\Note: Like English, a horizontal line can only go from left to right, and a vertical line can only go from top to bottom.\n\nHints: W = three (peaks) & two (valleys), M = three legs, V = split, D = toward left, H = the horizontal line, Y = the first stroke, K = crossing in the middle."),
  Local(127, ""),
  Local(128, "Please choose the key that maps the above Component."),
  Local(129, "Remember the above Expanded Components, then choose their corresponding key."),
  Local(130, "Please choose the key group that matches the above Component group."),
  Local(131, "The above chart shows the Expanded Components for Lead Component '日'（key B). They look similar to their Lead Component and type the same key (letter B).\n\nThe rules of Component order in a character: top before bottom; left before right; outside before inside.\n\nWe'll go through the Expanded Components for each Lead Component/key."),
  Local(132, "Note: The Expanded Components have similar shapes to their Lead Component."), // TODO: not used
  Local(133, "You remember the Components by group! In the next exercise, you will review the Components."),
  Local(134, "Way to go!"),
  Local(135, "You know your Lead Components! Let’s test your knowledge with some guided typing."),
  Local(136, "Wow!"),
  Local(137, "You know your Expanded Components! Let’s review it in next exercise."),
  Local(138, "Next"),
  Local(139, "Character review"),
  Local(140, "Glossary"),
  Local(141, "Privacy policy"),
  Local(142, "About the First Character Dictionary"),
  Local(143, "The First Character Dictionary is organized according to the first Basic Character contained in a Character. It houses nearly 3,800 Characters, all listed under their corresponding Basic Character. Each number in the Basic Character Table represents the number of strokes for each Basic Character in that group."),
  Local(144, "Navigate the First Character Dictionary"),
  Local(145, "Open the Basic Character Table"),
  Local(146, "Tap the first Basic Character contained in the Character that you are searching for"),
  Local(147, "Select the Character from the list. Note: If it’s not there, the dictionary doesn’t support this character."),
  Local(148, "View the detailed information about the Character"),
  Local(149, "Identify the Character’s first Basic Character"),
  Local(150, "Ex: Character 你 -> Basic Character 小 (the first and only Basic Character)"),
  Local(151, "If a Character’s first Basic Character is 口, but it contains other Basic Characters, select the next Basic Character"),
  Local(152, "Ex: 听 -> 斤 (skip 口)"),
  Local(153, "If a Character doesn’t contain any Basic Characters, select the Character’s first stroke (first five in the chart)"),
  Local(154, "Ex: Character 扎 -> Stroke 一 "),
  Local(155, "Ex: Character 丝 -> Stroke 乙. Note: all fold strokes map to 乙."),
  Local(156, "What are Components?"),
  Local(157, "Components are elements of a Character. The Quanzi Input Method breaks Components into two types. Lead Components are the base Components. And each Lead Component houses a collection of sub-components called Expanded Components."),
  Local(158, "How it works"),
  Local(159, "The Quanzi Input Method matches each Lead Component with a key on the English keyboard to create a Component-key pairing. Reference this chart to visualize how Lead Components are mapped to English letters."),
  Local(160, "Expanded Components are grouped under each Lead Component-key pairing. To type in Chinese, first break a character into a sequence of Components， then the sequence of Components are converted into sequences of English letters to be entered into computer."),
  Local(161, "The Chinese input method section of this app will:"),
  Local(162, "Introduce you to Lead & Expanded Components"),
  Local(163, "Teach you the Component-key pairings and typing method"),
  Local(164, "Help you memorize the Component-key pairings"),
  Local(165, "Help and guide you practice typing"),
  Local(166, "By the time you finish, you’ll be ready to type in Chinese on your own!"),
  Local(167, "Tips"),
  Local(168, "Tip 1: Want to use what you type elsewhere? Double click the content in the editing field to copy."),
  Local(169, "Tip 2: The Dos and Don’ts of breaking up a Character into Components."),
  Local(170, "DON’T break up Strokes that cross through each other."),
  Local(171, "ex: Character 井 doesn’t split into separate Components"),
  Local(172, "DO break up two strokes that are next to each other or just touching."),
  Local(173, "ex: 明 -> 日 and 月"),
  Local(174, "ex: 古 -> 十 and 口"),
  Local(175, "DO break up Characters into as few Components as possible."),
  Local(176, "ex: 房 -> 户 and 方 (instead of four Components)"),
  Local(177, "DO break up Characters into the Component with the most  strokes."),
  Local(178, "ex: 云 -> 一 (plus another Component with three strokes)"),
  Local(179, "Tip 3: The Lead Components and their keyboard pairings are visualized on the keyboard chart above."),
  Local(180, "Tap each Lead Component in the chart to see the Expanded Components associated to them."),
  Local(181, "During typing, select upper case letter 'Z' to show the Component-key pairings. Select upper case letter 'A' to 'Y' to show the Expanded Components."),
  Local(182, "To type a Lead Component or its Expanded Component, simply type the corresponding keyboard key."),
  Local(183, "Tip 4: Use this table to learn all the Strokes."),
  Local(184, "How to type a Chinese Character"),
  Local(185, "Divide the character into components (Lead Components or Expanded Components)."),
  Local(186, "If a Character has one Component:"),
  Local(187, "Type the Component"),
  Local(188, "If the Character doesn’t appear on the list:"),
  Local(189, "Type up to three make-up Strokes (the first, second, and the last stroke of the Component) until the Character appears"),
  Local(190, "Treat all fold Strokes as stroke '乙' (which is also a Component)"),
  Local(191, "If a Character has two Components:"),
  Local(192, "Type the two Components first"),
  Local(193, "If the Character doesn’t appear on the list:"),
  Local(194, "Type two make-up Strokes (the last Stroke of each Component) until the Character appears"),
  Local(195, "Treat all fold Strokes as a Component 乙"),
  Local(196, "If a Character has three or more Components:"),
  Local(197, "Type as many Components as necessary in sequence until the Character appears"),
  Local(198, "In action"),
  Local(199, "Ex: Type the Chinese character 品"),
  Local(200, "Find the first Component 口"),
  Local(201, "Find the corresponding key i"),
  Local(202, "Tap it"),
  Local(203, "If 品 appears in the Character list (below the editing field), select it by:"),
  Local(204, "Tapping the Character"),
  Local(205, "Tapping the spacebar if it’s first in the list"),
  Local(206, "Typing the number associated with the character"),
  Local(207, "If the Character is not listed, repeat these steps with the second and third Components until you see 品 listed"),
  Local(208, "The English letters in the editing field automatically convert to 品."),
  Local(209, "Terminology"),
  Local(210, "Hanzi"),
  Local(211, "Chinese character"),
  Local(212, "Hanzishu"),
  Local(213, "Hanzishu literally translates to ‘Chinese character tree’. Hansizhu is a learning method which breaks up Chinese Characters into Components. This system is used to search through the Chinese dictionary as well as to teach reading and typing in Chinese."),
  Local(214, "Strokes"),
  Local(215, "The lines used to create a Character (or a Component)."),
  Local(216, "Components"),
  Local(217, "Elements of a Character. There are two types of Components:"),
  Local(218, "Components that are also Characters (Basic Characters)"),
  Local(219, "Non-Character Components. They require other Components to create a Character."),
  Local(220, "Basic Characters"),
  Local(221, "Standalone Components. Basic Characters are the foundation of the First Character Dictionary."),
  Local(222, "Characters"),
  Local(223, "Characters are created with Components or Strokes."),
  Local(224, "Lead Components"),
  Local(225, "The basic Components which are mapped to a key on the English keyboard."),
  Local(226, "Select upper case letter 'Z' to show the Component-key pairings while typing."),
  Local(227, "Expanded Components"),
  Local(228, "The Components that stem from a Lead Component. Expanded Components usually have a similar shape to its Lead Component."),
  Local(229, "Select upper case letter 'A' to 'Y' to show the Expanded Components while typing."),
  Local(230, "Make-up Strokes"),
  Local(231, "The Strokes used to complete typing of Characters which contains only one or two Components."),
  Local(232, "Component-key pairing"),
  Local(233, "A Lead Component and its corresponding key on the English keyboard."),
  Local(234, "Mapping"),
  Local(235, "The concept of matching Lead Components to the English keyboard."),
  Local(236, "Quanzi Input Method"),
  Local(237, "A methodology of learning and typing Chinese by breaking up Characters into Components and mapping those core Components (Lead Components) to the English keyboard. All other Components (Expanded Components) are sorted under each Lead Component (often with a similar shape). Components are grouped into sequences of English letters. These sequences create Characters. Supports nearly 3,800 Characters."),
  Local(238, "A separate general purpose IME app for the input method to be used by other programs is under development and could be released at any time."),
  Local(239, "First Character Dictionary"),
  Local(240, "A Chinese Character dictionary that’s organized based on Basic Characters. Searching a Character by searching the first Basic Character it contains."),
  Local(241, "Sections"),
  Local(242, "Lessons"),
  Local(243, "Practice your Chinese with 10 units of lessons (60 lessons total)."),
  Local(244, "Please return to this section once you have mastered the Quanzi Input Method."),
  Local(245, "Character drills"),
  Local(246, "Learn Characters via a navigation tree. Includes definition, pronunciation, writing how-to, and the Basic Characters. It is a recursive tree with Components forming complicated Characters. It is visualized with the Character in the center of the screen and the Components/Characters (situated on all four sides of the screen) building up the central Character one layer at a time. Tapping a Character in the center drills down, and tapping a Component/Character on the sides moves back. Holding a Character/Component displays its detailed information."),
  Local(247, "Flashcards"),
  Local(248, "Reviews all the new Basic Characters, non-characters, and phrases from a lesson. Includes pronunciation, definition, strokes, and the Component-key pairing sequence."),
  Local(249, "Character breakdown"),
  Local(250, "Separates Characters in a lesson into Characters or Components. Tapping a Character or a Component displays its detailed information."),
  Local(251, "Conversation"),
  Local(252, "Demonstrates pronunciation and provides speaking practice. Tapping a Character displays its overlay information."),
  Local(253, "Typing exercises"),
  Local(254, "Practice for typing the Character using the Quanzi Input Method."),
  Local(255, "Quiz"),
  Local(256, "Reviews the lesson."),
  Local(257, "Dictionary"),
  Local(258, "View all the characters based on the First Character Dictionary method which groups Characters by their Basic Characters. Contains nearly 3,800 Characters."),
  Local(259, "Reference the Dictionary as you learn the Quanzi Input Method and complete the lessons."),
  Local(260, "Typing"),
  Local(261, "Learn the Quanzi Input Method and memorize the Component-key pairings."),
  Local(262, "Start in this section before continuing to the Lessons section."),
  Local(263, "Me"),
  Local(264, "Track your progress and review what you’ve already covered."),
  Local(265, "Character review"),
  Local(266, "Review the characters according to the lessons and the units that they were first introduced."),
  Local(267, "Quiz results"),
  Local(268, "Records of the quizzes that you have taken"),
  Local(269, "Icons"),
  Local(270, "Triangle"),
  Local(271, "Indicates a new Character or Component in the lesson."),
  Local(272, "Pencil"),
  Local(273, "Tap to draw the Character or component"),
  Local(274, "Speaker"),
  Local(275, "Tap to hear the Component, the Character or sentence"),
  Local(276, "Check mark"),
  Local(277, "Indicates that you have just gone through this Character or Component."),
  Local(278, "Overlay"),
  Local(279, "Tapping or holding a Character in many features within the app displays the detailed information about that Character."),
  Local(280, "Reminder: You should finish the typing course from the main menu before this exercise."),
  Local(281, "Note: Type uppercase letter Z to show components to keyboard mapping."),
  Local(282, "Note: Type uppercase letter A to Y to show Expanded Components. Type Z to show mapping."),
  Local(283, "Incorrect."),
  Local(284, "Correct! "),
  Local(285, "Continue"),
  Local(286, "Ok"),
  Local(287, "You’ve mastered all six Component groups! In the next exercise, you will memorize the Components in each group."),
  Local(288, "Exercise selection"),
  Local(289, "Practice typing 3,800 Characters in 38 exercises，with each containing about 100 characters."),
  Local(290, "Review selection"),
  Local(291, "Starting Unit"),
  Local(292, "Ending Unit"),
  Local(293, "Starting Lesson"),
  Local(294, "Ending Lesson"),
  Local(295, "Lesson"),
  Local(296, "Review"),
  Local(297, "Hanzishu App doesn't collect sensitive user specific data."),
  Local(298, "Tap 人 in the list below."),
  Local(299, "Type 'r', spacebar."),
  Local(300, "spacebar."),
  Local(301, "Start"),
  Local(302, "Language setting"),
  Local(303, "Language in title:"),
  Local(304, "Breakdown"),
  Local(305, "Diamond"),
  Local(306, "To show the detailed breakdown info."),
  Local(307, "to"),
  Local(308, "Review Expanded Components"),
  Local(309, "For the above Expanded Component, guess its Lead Component and type corresponding key."),
  Local(310, "You know your Expanded Components! Let’s review them in next exercise."),
  Local(311, "You really know your Expanded Components! Let’s practice with some typing exercises."),
  Local(312, "Reminder: For a character containing a single component, first type the component, then if needed, you can continue to type up to three strokes of the character: 1st, 2nd and last stroke."),
  Local(313, "Reminder: For a character containing two components, first type the two components, then if needed, you can continue to type up to two strokes: the last stroke from the 1st component, and the last stroke from the 2nd component."),
  Local(314, "If there are two options to separate components, choose the option that contains a component with more strokes."),
  Local(315, "closed shape"),
  Local(316, "facing right"),
  Local(317, "open to right"),
  Local(318, "curve toward bottom left"),
  Local(319, "overall T shape looking"),
  Local(320, "hammer looking"),
  Local(321, "disconnected triangle"),
  Local(322, "a shape with three legs"),
  Local(323, "half circle"),
  Local(324, "shape with three or two (lines)"),
  Local(325, "a body with two legs"),
  Local(326, "facing left"),
  Local(327, "closed shape with horizontal lines"),
  Local(328, "Learn Attached Components"),
  Local(329, "Learn Twin Components"),
  Local(330, "Learn Sub Components"),
  Local(331, "Characters with single Component"),
  Local(332, "Characters with two Components"),
  Local(333, "General Exercises"),
  Local(334, "Practice Expanded Components"),
  Local(335, "Over 80% of the characters are consisted of the Expanded Components. Remember them well will speed up the typing process.\n\nIn each of the following exercises, we'll display all the Expanded Components of one or two relevant Lead Components for your reference.\n\n"),
  Local(336, "A Lead/Expanded Component might contain some Attached Components. Use the same key of the Component to type the Attached Components.\n\nThe following chart shows the components in key 'F' that own some Attached Components. We'll go through them one key at a time.\n\n"),
  Local(337, "A Lead/Expanded Component might contain some Twin Components, which look almost same. Use the same key of the Component to type the Twin Components. \n\nThe following chart shows the components in key 'X' that own some Twin Components. We'll go through one key at a time.\n\n"),
  Local(338, "A Lead/Expanded Component might contain some subsets which are also Components. We call these subsets within a component Sub Components, although they are also Components by definition. Use the same key of the component to type those Sub Components. \n\nThe following chart shows the Components in key 'X' that contain Sub Components. We'll go through one key at a time.\n\n"),
  Local(339, "For a character containing only one component, first type the component. Then type the first two subcomponents of the Component.\n\nThe rules for breaking a Component into subcomponents are same as for breaking a character into components, except you can break lines that are crossing through each other if you have no other options.\n\nFor example, to type a single-component character '吏', first type Component '吏'(D), then break '吏' into '一' and '史', then type in '一'(H) and '史'(D). We'll go through some exercises.\n\nDuring breaking up, a few strokes and shapes are not components, and we match them to the closest components as shown below."),
  Local(340, "For a character containing two Components, first type the two Components. Then type the first two subcomponents of the second Component.\n\nWe'll go through some exercises.\n\n"),
  Local(341, "You have learned everything! Let's do some general exercises to complete the typing course.\n\n"),
  Local(342, "the verticle line"),
  Local(343, "Overall L shape looking"),
  Local(344, "the horizontal line"),
  Local(345, "open to top"),
  Local(346, "crossing at middle"),
  Local(347, "split shapes"),
  Local(348, "open to bottom"),
  Local(349, "shelter looking"),
  Local(350, "diagonal crossing"),
  Local(351, "closed shape with crossing"),
  Local(352, "the first stroke"),
  Local(353, "upward arrow"),
  Local(354, "You have completed this exercise! Please move on to the next one."),
  Local(355, "You have completed all the typing exercises! You can now start your own free typing or do some optional customized typing exercises."),
  Local(356, "Expanded Components are very important! Let's practice them one more time before moving on."),
  Local(357, "Let's start"),
];