// TODO: Dont think it works/helps, and could remove later

include: package:lints/recommended.yaml

analyzer:
  exclude:
   - lib/main.dart
  //language:
  //  strict-casts: true
  //  strict-raw-types: true

linter:
  rules:
    - cancel_subscriptions
